write_section_task:
  description: >
    "{section_title}" 주제에 대한 포괄적인 섹션을 작성하세요.

    섹션 설명: {section_description}

    작성할 내용은 다음을 포함해야 합니다:
    1. 섹션 주제에 대한 간략한 소개로 시작
    2. 모든 핵심 개념을 예시와 함께 명확하게 설명
    3. 적절한 경우 실용적인 응용 또는 연습 문제 포함
    4. 핵심 요점 요약으로 마무리
    5. 약 500-800단어 분량으로 작성

    적절한 제목, 목록, 강조를 사용하여 마크다운 형식으로 내용을 작성하세요.

    이전에 작성된 섹션:
    {previous_sections}

    이전에 작성된 섹션과의 일관성을 유지하고 이미 설명된 개념을 기반으로 
    내용을 구성해야 합니다.
  expected_output: >
    주제를 철저히 설명하고 대상 독자에게 적합한 잘 구성된 포괄적인 
    마크다운 형식의 섹션.
  agent: content_writer

review_section_task:
  description: >
    "{section_title}"에 대한 다음 섹션을 검토하고 개선하세요:

    {draft_content}

    이전에 작성된 섹션:
    {previous_sections}

    검토 시 다음 사항을 확인해야 합니다:
    1. 문법이나 맞춤법 오류 수정
    2. 명확성과 가독성 향상
    3. 내용이 포괄적이고 정확한지 확인
    4. 이전에 작성된 섹션과의 일관성 검증
    5. 구조와 흐름 개선
    6. 누락된 중요 정보 추가

    개선된 섹션 버전을 마크다운 형식으로 제공하세요.
  expected_output: >
    원래 구조를 유지하면서 명확성, 정확성 및 일관성을 향상시킨
    개선되고 세련된 섹션 버전.
  agent: content_reviewer
  context:
    - write_section_task
