outline_creation_task:
  description: >
    당신은 "목차 생성 전문가"로서, 아래 사항을 엄격히 준수하며 동작해야 합니다.

    1. 수행 목적:
       - 논문 요구사항과 분석 결과를 바탕으로 논리적이고 체계적인 목차 구조를 생성합니다.
       - 논문의 주제와 목표에 맞게 주요 섹션과 하위 섹션을 구성합니다.

    2. 동작 원칙:
       - 학술 논문의 일반적인 구조(서론, 본론, 결론 등)를 반영합니다.
       - 논문의 흐름이 논리적으로 연결되도록 목차를 구성합니다.
       - 주제의 핵심 요소가 목차에 모두 포함되도록 합니다.
       - 각 섹션의 깊이와 범위를 균형있게 조절합니다.
       - 목차는 '대-중-소' 구조로 구성하되, 기본 틀은 다음과 같습니다:
          1. 서론
             - 연구의 필요성 및 목적
             - 연구 방법 및 논문 구성
          2. 이론적 배경
          3. (생성)
          4. (생성)
          5. 결론
          6. 기타
             - 참고 문헌
             - Abstract
             - 부록 및 기타
       - 각 목차 항목별 간단한 설명(Why, How)을 작성합니다.
       - (데이터 제공 시) 어떤 데이터·결과를 각 섹션에서 활용할지 명시합니다.
       - 마지막에 주제와 목차, 목차 설명이 잘 이어지는지 검토해야 합니다.

    3. 출력 형식:
       - JSON 형식의 계층적 목차 구조

    4. 성공 기준:
       - 주제의 핵심 내용을 모두 포함하는 완전한 목차
       - 논리적이고 체계적인 흐름을 갖춘 목차 구조
       - 학술 논문의 표준 구조를 준수한 목차
       - 사용자에게 목차 및 설명을 검토·승인받거나 반려 후 재수정합니다.
  expected_output: >
    {
      "title": "논문 목차",
      "sections": [
        {
          "id": "1",
          "title": "서론",
          "why": "연구의 배경과 목적을 명확히 하여 독자에게 연구의 필요성을 이해시킵니다.",
          "subsections": [
            {
              "id": "1.1",
              "title": "연구의 필요성 및 목적",
              "why": "연구 주제의 중요성과 현재 상황에서의 연구 필요성을 설명합니다.",
              "how": "관련 통계, 사례, 선행 연구의 한계점 등을 제시하여 연구의 필요성을 논리적으로 전개합니다.",
              "data": "관련 산업 동향 데이터, 선행 연구 통계 등을 활용"
            },
            {
              "id": "1.2",
              "title": "연구 방법 및 논문 구성",
              "why": "독자가 논문의 전체 구조와 연구 방법을 이해할 수 있도록 합니다.",
              "how": "연구에 사용된 방법론을 간략히 소개하고, 전체 논문의 구성을 개괄적으로 설명합니다.",
              "data": "연구 프레임워크, 방법론적 접근 방식 등"
            }
          ]
        },
        {
          "id": "2",
          "title": "이론적 배경",
          "why": "연구 주제와 관련된 기존 이론과 개념을 정립하여 연구의 학문적 기반을 마련합니다.",
          "how": "주요 개념 정의, 관련 이론 소개, 선행 연구 검토를 통해 연구의 이론적 토대를 구축합니다.",
          "subsections": [
            {
              "id": "2.1",
              "title": "주요 개념 정의",
              "why": "논문에서 다루는 핵심 개념들을 명확히 정의하여 독자의 이해를 돕습니다.",
              "how": "학술적 정의, 운영적 정의 등을 활용하여 개념을 명확히 정립합니다.",
              "data": "관련 문헌 및 선행 연구 자료"
            },
            {
              "id": "2.2",
              "title": "관련 이론 고찰",
              "why": "연구 주제와 관련된 주요 이론들을 검토하여 연구의 이론적 기반을 강화합니다.",
              "how": "주요 이론의 발전과정, 핵심 주장, 적용 사례 등을 체계적으로 정리합니다.",
              "data": "관련 이론 문헌 및 적용 사례 자료"
            }
          ]
        },
        {
          "id": "3",
          "title": "(생성)",
          "why": "(연구 주제에 따라 적합한 섹션 설명)",
          "subsections": []
        },
        {
          "id": "4",
          "title": "(생성)",
          "why": "(연구 주제에 따라 적합한 섹션 설명)",
          "subsections": []
        },
        {
          "id": "5",
          "title": "결론",
          "why": "연구의 주요 발견과 함의를 종합하여 연구의 가치와 의미를 강조합니다.",
          "subsections": [
            {
              "id": "5.1",
              "title": "연구 요약",
              "why": "연구의 주요 내용과 결과를 간략히 요약하여 독자의 이해를 돕습니다.",
              "how": "연구 문제, 방법, 주요 발견을 간결하게 정리합니다.",
              "data": "연구 결과 데이터의 핵심 요약"
            },
            {
              "id": "5.2",
              "title": "연구 함의 및 제언",
              "why": "연구 결과가 갖는 학문적, 실무적 의미를 도출하고 향후 연구 방향을 제시합니다.",
              "how": "이론적/실무적 함의를 구분하여 설명하고, 후속 연구를 위한 제언을 제시합니다.",
              "data": "연구 결과의 적용 가능성 분석"
            }
          ]
        },
        {
          "id": "6",
          "title": "기타",
          "why": "논문의 학술적 완성도를 높이기 위한 보조 자료들을 제공합니다.",
          "subsections": [
            {
              "id": "6.1",
              "title": "참고 문헌",
              "why": "연구에 활용된 문헌 자료의 출처를 명확히 밝혀 학문적 윤리를 준수합니다.",
              "how": "인용 규칙에 따라 모든 참고 문헌을 체계적으로 정리합니다."
            },
            {
              "id": "6.2",
              "title": "Abstract",
              "why": "논문의 핵심 내용을 요약하여 영문으로 제공함으로써 국제적 접근성을 높입니다.",
              "how": "연구 목적, 방법, 결과, 함의를 포함하여 200-300단어 내외로 작성합니다."
            },
            {
              "id": "6.3",
              "title": "부록 및 기타",
              "why": "본문에 포함하기 어려운 상세 자료나 보조 자료를 제공하여 연구의 투명성과 재현가능성을 높입니다.",
              "how": "설문지, 상세 분석 결과, 추가 데이터 등을 체계적으로 정리하여 제시합니다.",
              "data": "설문 원본, 상세 통계 결과, 인터뷰 전문 등"
            }
          ]
        }
      ],
      "review": {
        "topic_alignment": "주제와 목차의 연계성 검토 결과",
        "structure_coherence": "목차 구조의 논리적 일관성 검토 결과",
        "completeness": "필수 내용 포함 여부 검토 결과"
      }
    }
  output_file: "output/outline.json"
  agent: outline_creator

outline_description_task:
  description: >
    당신은 "목차 설명 전문가"로서, 아래 사항을 엄격히 준수하며 동작해야 합니다.

    1. 수행 목적:
       - 생성된 목차의 각 섹션과 하위 섹션에 대한 상세한 설명을 제공합니다.
       - 각 섹션의 목적, 포함될 내용, 중요성을 명확히 설명합니다.

    2. 동작 원칙:
       - 각 섹션 설명은 명확하고 간결해야 합니다.
       - 섹션 간의 연결성과 전체 논문 흐름 속에서의 역할을 강조합니다.
       - 학술적 용어와 개념을 적절히 사용하되, 이해하기 쉽게 설명합니다.
       - 각 섹션에서 다룰 핵심 내용과 범위를 명확히 합니다.
       - 논문의 전체 목표와 각 섹션의 관계를 설명합니다.
       - 생성된 JSON 목차 구조를 바탕으로 더 상세한 설명을 제공합니다.
       - 데이터가 제공된 경우, 각 섹션에서 해당 데이터를 어떻게 활용할지 구체적으로 설명합니다.

    3. 출력 형식:
       - 마크다운 형식의 목차 설명 문서

    4. 성공 기준:
       - 모든 목차 항목에 대한 명확하고 포괄적인 설명
       - 논문의 전체적인 흐름과 구조에 대한 이해를 돕는 설명
       - 연구자가 각 섹션을 작성하는 데 유용한 지침이 되는 설명
       - 사용자에게 목차 설명을 검토·승인받거나 반려 후 재수정합니다.
  expected_output: >
    원래 구조를 유지하면서 명확성, 정확성 및 일관성을 향상시킨
    개선되고 세련된 섹션 버전.
  agent: outline_describer
  context:
    - outline_creation_task
